{
    'name': 'Estate Count',
    'version': '15.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'management Tutorials For Beginners',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'B.N.Son',
    'maintainer': '',
    'website': '',
    'live_test_url': '',
    'depends': ['estate', 'hr'],
    'demo': [],
    'data': [
        # 'views/estate_inherit_view.xml',
    ],
    # 'css': ['static/src/css/styles.css'],
    # 'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
