from . import res_intern_users
from . import students
from . import courses
from . import classes
from . import teachers
from . import plans
from . import instructors
from . import councils
from . import partners
from . import inherit_demo
