{
    'name': 'internship management',
    'version': '12.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'management Tutorials For Beginners',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'Odoo Mates',
    'maintainer': '',
    'website': '',
    'live_test_url': '',
    'depends': ['project'],
    'demo': [],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'data/sequence.xml',
        # 'data/data.xml',
        # 'data/cron.xml',
        # 'wizards/create_appointment.xml',
        'views/courses.xml',
        'views/classes.xml',
        'views/students.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}